<?php $m = $formMedicine ?? []; ?>
<div class="col-12"><label class="form-label">Generic Name *</label><input class="form-control" name="name" required value="<?= htmlspecialchars($m['name'] ?? '') ?>"></div>
<div class="col-md-6"><label class="form-label">Brand Name</label><input class="form-control" name="brand_name" value="<?= htmlspecialchars($m['brand_name'] ?? '') ?>"></div>
<div class="col-md-6"><label class="form-label">Strength</label><input class="form-control" name="strength" value="<?= htmlspecialchars($m['strength'] ?? '') ?>"></div>
<div class="col-md-6"><label class="form-label">Category *</label><select class="form-select" name="category"><?php foreach (['Antimalarial','Antibiotic','Analgesic','Maternal Care','Emergency','Surgical','Vaccine','IV Fluid','Antidiabetic','Pediatrics','Other'] as $opt): ?><option <?= (($m['category'] ?? '')===$opt)?'selected':''; ?>><?= $opt ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Dosage Form</label><select class="form-select" name="dosage_form"><?php foreach (['Tablet','Capsule','Injection','IV Fluid','Powder','Kit','Unit'] as $opt): ?><option <?= (($m['dosage_form'] ?? '')===$opt)?'selected':''; ?>><?= $opt ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">SKU</label><input class="form-control" name="sku" value="<?= htmlspecialchars($m['sku'] ?? '') ?>"></div>
<div class="col-md-6"><label class="form-label">Unit Cost (MZN)</label><input class="form-control" type="number" name="unit_cost" value="<?= htmlspecialchars((string)($m['unit_cost'] ?? '')) ?>"></div>
<div class="col-md-6"><label class="form-label">Current Stock</label><input class="form-control" type="number" name="stock" value="<?= htmlspecialchars((string)($m['stock'] ?? '')) ?>"></div>
<div class="col-md-6"><label class="form-label">Reorder Point</label><input class="form-control" type="number" name="reorder_point" value="<?= htmlspecialchars((string)($m['reorder_point'] ?? '')) ?>"></div>
<div class="col-md-6"><label class="form-label">Reorder Quantity</label><input class="form-control" type="number" name="reorder_qty" value="<?= htmlspecialchars((string)($m['reorder_qty'] ?? '')) ?>"></div>
<div class="col-md-6"><label class="form-label">Avg Monthly Usage</label><input class="form-control" type="number" name="avg_monthly_usage" value="<?= htmlspecialchars((string)($m['avg_monthly_usage'] ?? '')) ?>"></div>
<div class="col-md-6"><label class="form-label">Storage Requirements</label><select class="form-select" name="storage"><?php foreach (['Room Temperature','Cool & Dry','Refrigerated','Frozen'] as $opt): ?><option <?= (($m['storage'] ?? '')===$opt)?'selected':''; ?>><?= $opt ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach (['In Stock','Low Stock','Out of Stock','Overstocked'] as $opt): ?><option <?= (($m['status'] ?? '')===$opt)?'selected':''; ?>><?= $opt ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Facility</label><input class="form-control" name="facility" value="<?= htmlspecialchars($m['facility'] ?? 'Maputo Central') ?>"></div>
<div class="col-md-6"><label class="form-label">Department</label><input class="form-control" name="department" value="<?= htmlspecialchars($m['department'] ?? 'Pharmacy') ?>"></div>
<div class="col-md-6"><label class="form-label">Expiry Date</label><input class="form-control" type="date" name="expiry_date" value="<?= htmlspecialchars($m['expiry_date'] ?? '') ?>"></div>
<div class="col-md-6 d-flex gap-4 align-items-center pt-4"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_essential" value="1" <?= !empty($m['is_essential'])?'checked':''; ?>><label class="form-check-label">Essential Medicine</label></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_critical" value="1" <?= !empty($m['is_critical'])?'checked':''; ?>><label class="form-check-label">Critical / Emergency</label></div></div>
<div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"><?= htmlspecialchars($m['notes'] ?? '') ?></textarea></div>
