<section class="page-body compact-page">
  <div class="section-head mb-3">
    <div>
      <h2>User Administration</h2>
      <p class="text-muted mb-0">Manage access, reset passwords, deactivate users, and assign roles.</p>
    </div>
    <button class="btn btn-alk" data-bs-toggle="modal" data-bs-target="#addUserModal"><i class="bi bi-person-plus"></i> Add User</button>
  </div>
  <div class="card alk-card"><div class="card-body"><div class="table-responsive"><table class="table inventory-table align-middle"><thead><tr><th>Name</th><th>Role</th><th>Facility</th><th>Status</th><th>Password</th><th>Actions</th></tr></thead><tbody><?php foreach($usersList as $u): ?><tr><td><strong><?= htmlspecialchars($u['name'] ?? '') ?></strong><div class="small text-muted"><?= htmlspecialchars($u['email'] ?? '') ?></div></td><td><?= htmlspecialchars($u['role'] ?? '') ?></td><td><?= htmlspecialchars($u['facility'] ?? '') ?></td><td><span class="pill-status <?= str_contains(strtolower($u['status'] ?? ''), 'active') ? 'in-stock' : 'low-stock' ?>"><?= htmlspecialchars($u['status'] ?? '') ?></span></td><td><span class="tiny text-muted"><?= htmlspecialchars($u['password'] ?? 'hidden') ?></span></td><td class="d-flex gap-2 flex-wrap"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editUser<?= (int)($u['id'] ?? 0) ?>">Edit</button><?php if(($u['status'] ?? 'Active')==='Active'): ?><a class="btn btn-sm btn-outline-warning" href="index.php?route=users&action=deactivate&id=<?= (int)($u['id'] ?? 0) ?>">Deactivate</a><?php else: ?><a class="btn btn-sm btn-outline-success" href="index.php?route=users&action=activate&id=<?= (int)($u['id'] ?? 0) ?>">Activate</a><?php endif; ?><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#resetUser<?= (int)($u['id'] ?? 0) ?>">Reset Password</button><a class="btn btn-sm btn-outline-danger" href="index.php?route=users&action=delete&id=<?= (int)($u['id'] ?? 0) ?>" onclick="return confirm('Delete this user?')">Delete</a></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</section>

<div class="modal fade" id="addUserModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post"><input type="hidden" name="action" value="add-user"><div class="modal-header"><h5 class="modal-title">Add User</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-md-6"><label class="form-label">Full Name</label><input class="form-control" name="name" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" required></div><div class="col-md-4"><label class="form-label">Role</label><select class="form-select" name="role"><?php foreach ($rolesList as $role): ?><option><?= htmlspecialchars($role['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Facility</label><select class="form-select" name="facility"><?php foreach ($facilities as $f): ?><option><?= htmlspecialchars($f['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><option>Active</option><option>Pending Onboarding</option><option>Suspended</option></select></div><div class="col-md-6"><label class="form-label">Password</label><input class="form-control" name="password" value="password123"></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-alk">Create User</button></div></form></div></div></div>

<?php foreach($usersList as $u): ?>
<div class="modal fade" id="editUser<?= (int)$u['id'] ?>" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post"><input type="hidden" name="action" value="edit-user"><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><div class="modal-header"><h5 class="modal-title">Edit User</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-md-6"><label class="form-label">Full Name</label><input class="form-control" name="name" value="<?= htmlspecialchars($u['name']) ?>"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?= htmlspecialchars($u['email']) ?>"></div><div class="col-md-4"><label class="form-label">Role</label><select class="form-select" name="role"><?php foreach ($rolesList as $role): ?><option <?= $u['role']===$role['name']?'selected':''; ?>><?= htmlspecialchars($role['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Facility</label><select class="form-select" name="facility"><?php foreach ($facilities as $f): ?><option <?= $u['facility']===$f['name']?'selected':''; ?>><?= htmlspecialchars($f['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['Active','Pending Onboarding','Inactive','Suspended'] as $opt): ?><option <?= ($u['status']??'')===$opt?'selected':''; ?>><?= $opt ?></option><?php endforeach; ?></select></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-alk">Save</button></div></form></div></div></div>
<div class="modal fade" id="resetUser<?= (int)$u['id'] ?>" tabindex="-1"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><form method="post"><input type="hidden" name="action" value="reset-password"><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><div class="modal-header"><h5 class="modal-title">Reset Password</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">New Password</label><input class="form-control" name="password" value="password123"></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-alk">Reset</button></div></form></div></div></div>
<?php endforeach; ?>
